### ISSUE TITLE
O que aprender e como aprender

### ISSUE THREAD

**Issue by eduardobandeiramg** [training-center/forum#108]
Ola pessoal
Comecei um curso de engenharia recentemente e me apaixonei com programação quando tive essa matéria no primeiro período.
Tenho profundo interesse em aprender programação mobile e de software. Mas sei que aprender apenas isso não basta. 
Sei que também preciso saber sobre hardware, redes, banco de dados, SQL, API's etc etc.
Pensei em fazer um curso na Internet sobre TI pra aprender o básico sobre o mais geral e um curso de programação paralelamente. Estou com muita vontade de aprender, mas não sei que caminho seguir, as coisas que devo aprender. Estou meio perdido.
O que vocês me recomendam?
Obrigado e abs!

**Comment by guscsales** [comment]
Fala ai @Eduardobmg, blza?

Recentemente eu postei um [vídeo sobre como iniciar no mundo da programação](https://www.youtube.com/watch?v=kTviz8vBMCM), pode ser bem útil para você. Da uma olhada!

Té mais!

**Comment by afonsoaugusto** [comment]
Opa @Eduardobmg, tudo bom?
Hoje eu atuo com DevOps, mas uma dica de como iniciar que eu posso te dar é foque nos básicos.
Como vc está cursando Engenharia, quais matérias vc tem na sua grade?
Pq com base nas suas matérias vc pode ir ampliando, ai vc pode aproveitar o que vc está vendo e ampliar o conhecimento.
