### ISSUE TITLE
Como deixar aplicações mobile desenvolvidas em C# através da plataforma Xamarin.Forms adaptável em qualquer dispositivo como um site responsivo?

### ISSUE THREAD

**Issue by MarcosGOFavaretto** [training-center/forum#111]

**Comment by gustavomeia** [comment]
Qual seria a ideia de tela que está tentando desenhar? Dependendo da maneira que vc construir a tela ela já fica adaptável a resoluções diferentes. Caso precise exibir telas diferentes de acordo com a resolução acredito que vc consiga utilizando
[DeviceDisplay do Xamarin.Essentials](https://docs.microsoft.com/pt-br/xamarin/essentials/device-display?tabs=ios)

**Comment by MarcosGOFavaretto** [comment]
Olá Gustavo Meia, obrigado por responder 😁

Então, a respeito do projeto...se trata de um aplicativo que se pode navegar em três telas que meu grupo desenvolveu para o TCC no ano passado para nosso técnico em mecatrônica.
Quando fizemos, nos contentamos em fazer com que a aplicação se adaptasse apenas ao meu dispositivo, um Motorola G6 plus. Com isso, desenvolvemos o layout da tela no Photoshop CS6, o background foi incorporado ao projeto como uma imagem. Desta forma, a aplicação apenas estaria com seus itens bem posicionados em dispositivos como o meu.
Através do XAML fomos acertando o espaçamento dos itens que eram imagens, até ficarem bem posicionados na tela do meu smartphone.

**Comment by MarcosGOFavaretto** [comment]
...Obrigado pela dica, vou pesquisar o assunto 🤗

**Comment by gustavomeia** [comment]
Entendi, se for uma imagem o fundo que define onde os elementos devem estar ai realmente vai ser difícil (se não impossível) ter a mesma interface para tamanhos de tela diferentes.
Dependendo de como a tela esta desenhada e se a imagem for apenas um background (não definindo as posições dos elementos) posso tentar te ajudar, se quiser compartilhar seu xaml pra gente poder ter uma ideia melhor de como ele esta, ai fica mais fácil de encontrar soluções ;)

**Comment by MarcosGOFavaretto** [comment]
Que formas podem ser utilizadas para criar um layout responsivo?

**Comment by gustavomeia** [comment]
Da pra fazer com grid, flexlayout e outros... Cada tela tem um desafio que um elemento pode ser mais fácil de resolver que outros, mas com o grid da pra fazer muita coisa
