### ISSUE TITLE
Futuro do JS com o WebAssembly

### ISSUE THREAD

**Issue by jonatasarruda** [training-center/forum#29]
Fala galera, beleza?

Estou começando meus estudos de desenvolvimento front-end e estou curtindo bastante aprender sobre o que o JS é capaz. Porém eu acabei caindo no tópico WebAssembly, vi que isso meio que mata o uso do JS para aplicações Web, fazendo com que seja possível escrever o código em C++, por exemplo, e ele possa ser compilado para execução no navegador, até agora só vi coisas muito boas falando sobre essa técnica, que apesar de estar no "inicio", já aparenta está bem encaminhada. 

Eis a dúvida, devo não procurar tanto pelo JS e focar, talvez, em C++ que é pra onde as coisas estão começando a apontar ou eu posso continuar onde estou que ainda vai ter um tempo ate realmente o WebAssembly "pegar"?

**Comment by danilosilvadev** [comment]
Brow java dá pra fazer no front tbm e eu n ouço muito falar de páginas usando isso em comparação com js. JS é tão foda não por ser a única opção de mexer no frontend(até pq n é) mas por ser a melhor opção atualmente. JS tem um ecossistema gigantesco e a linguagem de programação mais usada no mundo atualmente. É um linguagem objetiva e cheia de recursos. Eu antes estudava java e depois q descobri o js mudei completamente minha visão. Aprenda o q vc quiser, mas se quer saber se webassembly vai fazer js perder sua importância no futuro isso ninguém sabe, o provável q webassembly seja só mais uma opção e q o trono de ferro continue com JS lannister sentado nele. hehehe

**Comment by jonatasarruda** [comment]
Não sei se seria bem assim... Entre Java e JS é bem claro a escolha do JS, por já ser pensado da forma que funcione bem na Web. O que é a mesma coisa do WebAssembly, imagine que você que já trabalha com Java a muito tempo e de tempos em tempos tem que fazer alguma coisa em JS, mas você sabe que poderia ser melhor se usasse uma outra linguagem pra isso... E é ai que o Wasm entra, ele consegue "traduzir" (entre aspas porque não é só uma questão de tradução) outras linguagem para JS e fazer com que esse código que foi "traduzido" seja mais rápido que se fosse escrito em JS diretamente.

Acho que o caminho natural seria, se existe a possibilidade, já começarmos a ver e aprender coisas que futuramente talvez venham a fazer parte do nosso cotidiano, não acho que seja tão seguro dizer que uma linguagem nunca deixará de estar onde está hoje porque, muitas empresas já apoiam o Wasm e acredito que isso já seja indicio de que algo possa mudar daqui a um tempo. Não vai ser da noite pro dia que isso irá acontecer, se vai, mas se quisermos estar na vanguarda temos que entender o que muda.

**Comment by danilosilvadev** [comment]
Então falei 'o provável'. Vc está falando sobre coisas futuras n dá pra saber, a realidade hj é js. No futuro td pode mudar, mas o q a tendência está mostrando é q provavelmente vai demorar. JS ainda está crescendo e ficando mais popular, n é como se estivesse demonstrando sinais de queda ainda.

**Comment by jonatasarruda** [comment]
Você deve estar certo, eu provavelmente estava overthinking nisso. Como é algo que eu tenho que empreender certo esforço queria ter a certeza e também queria saber o que a galera tinha a dizer. Provavelmente até lá já estarei "de boas" e a transição será natural. Continuarei com o JS! 😄

**Comment by danilosilvadev** [comment]
Brow, uma dica. Aprende o básico, faz uns katas [aqui](https://www.codewars.com) nesse site e compara. Eu passei quase um ano aprendendo java, e depois de um mês aprendendo js escolhi ele(java nunca mais buéee). No começo pensei no mercado, em motivos lógicos de performance, write less and do more e um monte de coisa. Mas no fundo foi por amor. hehe escolha a q vc sentir q vai ser divertido mexer. O mesmo aconteceu quando fui estudar angular e ae descobri o react S2. hehe Tanto js quanto C++ tem mercado, claro cada um na sua área, mas recomendo q estude pelo menos 1 mês sobre a linguagem pra tomar uma decisão tão séria hehe
