### ISSUE TITLE
Labels para este repo

### ISSUE THREAD

**Issue by lbighetti** [training-center/forum#3]
Sugire criarmos labels para quando uma pergunta for "respondida" marcarmos.
Assim conseguimos ver mais claramente qual issues já tem resposta e qual não, o que acham ?

**Comment by lbighetti** [comment]
O parâmetro pode ser tipo stackoverflow, quando o autor achar que sanou a dúvida ele comenta isso e marcamos com um label "respondido"

nada impede de continuar conversas lah e adicionar sugestoes, mas ai conseguimos focar em responder as coisas sem resposta também 👍

**Comment by alinebastos** [comment]
Acho ótimo o autor ter esse controle, gostei! :)

**Comment by woliveiras** [comment]
+1

**Comment by lbighetti** [comment]
toppers, fazendo aqui, vou fechar esse issue!
