### ISSUE TITLE
Qual distribuição Linux usar para desenvolver ?

### ISSUE THREAD

**Issue by AzevedoDev** [training-center/forum#34]
Estou começando agora na carreira dev e já gostaria de começar utilizando um sistema Unix pela facilidade de utilizar Git, NPM, e afins.
Estou focando no aprendizado em JS para utilizar Angular/React, dai eu gostaria de saber qual distro a galera mais está usando e qual são as vantagens da distro em especifico.

**Comment by jvrmaia** [comment]
Uso Linux desde o Slackware 9 e já passei por várias outras versões e já usei OSX e hoje estou no Ubuntu.

Minha motivação de usar o Ubuntu hoje é que já me basta as minhas aplicações em produção para ficar batendo cabeça e configurando, eu não preciso disso no meu desktop também.

É muito fácil achar qualquer how-to para os seus problemas no Ubuntu e ele é bem amigável. Existem algumas tretas sobre ele e algumas pessoas acabam escolhendo usar "forks" dele, por exemplo, o Mint. Eu tentei usar mas não vi vantagens e voltei p/ o Ubuntu.

Se não for p/ usar o Ubuntu acho que usaria o Arch Linux que foi um dos que mais usei também e tem uma wiki muito boa para ajudar com qualquer problema. Gostava dele por causa disso e manter os pacotes sempre os mais novos o possível.

Então, acho que vc deve levar isso em consideração, o quanto de dor de cabeça vc pretende passar com configurações de Linux?

**Comment by woliveiras** [comment]
Atualizei o título porque usamos labels pra especificar mais, @TheAzevedoMan :grin: 

Você poderia dizer um pouco mais sobre o seu caso e porque da sua dúvida?

**Comment by AzevedoDev** [comment]
Eu tenho dúvida no seguinte fator.

Estou começando agora na carreira dev e já gostaria de começar utilizando um sistema Unix pela facilidade de utilizar Git, NPM, e afins.
Estou focando no aprendizado em JS para utilizar Angular/React, dai eu gostaria de saber qual distro a galera mais está usando e qual são as vantagens da distro em especifico.

Valeu por ter editado o Titulo :D

**Comment by jvrmaia** [comment]
Acho que vc pode usar o ubuntu mesmo então.

Dica para instalar versões do Node: https://github.com/creationix/nvm

**Comment by robertopc** [comment]
Eu uso o Lubuntu LTS que é o Ubuntu com interface LXDE(bem leve). Acho o Ubuntu padrão um pouco lento, no caso a interface Unity. Prefiro uma interface leve que eu vou adicionando as coisas ao meu modo.

Geralmente as distros Linux não possuem muita diferença no uso, só mudam a interface gráfica, o gerenciador de pacotes e algumas configurações. Porém, te indico alguma distro derivada de Debian, por conta da estabilidade e quantidade de usuários, por consequência suporte.
Abaixo listo algumas distros que já usei e as experiências que tive:

**Ubuntu Latest** (rolling release, exemplo 17.10) - é a versão mais atualizada do Ubuntu, é interessante pra quem quer estar por dentro das últimas novidades. Porém, algumas atualizações podem quebrar alguma coisa no sistema. Já tive bastantes problemas por utilizar as versões latest.

**Ubuntu LTS** (long term support, exemplo 16.04) - essa é uma versão um pouco atrás no quesito novidades, porém é a versão mais estável e com o suporte mais longo. Perde um pouco nas novidades, mas ganha na estabilidade.

**Xubuntu LTS** - parecido com o Ubuntu LTS, só muda por utilizar a interface XFCE(leve) e alguns programas pré-instalados são diferentes.

**Lubuntu LTS** (a que uso no momento) - parecida com a Ubuntu LTS, mas com a interface LXDE(bem leve). Os programas pré-instalados são mais básicos e é bem crua. Boa pra quem gosta de personalizar mais a distro, pra quem não sabe pode acha-la ruim. Um programa indispensável nela é um App Launcher, tipo o: Albert, Synapse ou Cerebro.

**Debian** - é a mãe do Ubuntu e de 1M de outras distros. É conhecida por ser muito estável(por isso têm muitos filhos). Possui interface GNOME(que é interessante), porém é um pouco menos amigável que o Ubuntu, Mint e outros. Dá um pouco mais de trabalho pra usa-la.

**ElementaryOS** - é uma distro baseada no Ubuntu que é muito bonita e amigável. Ela é parecida com o Mac OSX.

**Comment by gutocosta** [comment]
Eu não sou desenvolvedor, mas uso distros Linux há algum tempo, em todo lugar (notebook, desktop, server). Comecei com o Ubuntu (na época dos Live-CD entregue em casa), fui pro Debian por indicação do [@aracnus](https://github.com/aracnus) (em uma Campus Party), e agora me rendi ao Arch Linux, depois que li um [post](http://www.akitaonrails.com/2017/01/10/arch-linux-best-distro-ever) do [@akitaonrails](https://github.com/akitaonrails) (ele já tinha publicado um [post](http://www.akitaonrails.com/2017/01/06/customizing-fedora-25-for-developers) sobre o Fedora).
Estou bem feliz com o Arch, uso em meu notebook e no desktop do trabalho.

PS: Eu gosto muito destas [entrevistas](http://setup.loopinfinito.com.br/sobre/), falando sobre o setup e o workflow de alguns programadores. (Conheci por exemplo o Spacemacs)

**Comment by giovannicruz97** [comment]
Olá! Eu usei Ubuntu (e sua família), durante muito tempo. Sempre teve uma pane ou algo que o Ubuntu falhava. Hoje, uso o Manjaro (Versão KDE). Sou muito feliz com essa distro. Como ela é baseada em Arch, então tem tudo na AUR e nos repositórios oficiais. Super indico! 👍

**Comment by DevEwertonOliveira** [comment]
Galera o que voces acham do Fedora Workstation?

**Comment by dyhalmeida** [comment]
Eu utilizo o deepin linux a quase um ano e é super banaca, fácil de utilizar e não sinto falta do windows. Tem a deepin store que você encontra todos os principais softwares a um click de uma instalação. Enfim, nota 10.

https://www.deepin.org/en/

**Comment by crisgon** [comment]
Também uso o Deepin. Sai do Windows tem pouco tempo, fui pro ubuntu, passei uma semana e fui pro Deepin. Não estou sentido falta de nada do windows. A adaptação é super tranquila e tem vários recursos bacanas nele, sem contar o desgin que é lindão!

**Comment by jamile-dev** [comment]
Estou usando o [Linux Mint](https://linuxmint.com/download.php) 18.3 Sylvia com o Cinnamon no momento e estou gostando! Tudo é muito fácil para instalar, a distro é leve e atualizada.
Porém já ouvi falar muito bem do Fedora e também do Deepin.
Uma coisa que me ajuda é fazer o pendrive de instalação com as distros e usar um pouco cada uma antes de realmente fazer a instalação. Assistir vídeos de review também me ajuda. Inclusive, este [canal](https://www.youtube.com/user/linuxscoop) têm vários vídeos com algumas distros. Espero que ajude!

**Comment by weltonsanches** [comment]
Também uso o Linux Mint com Cinnamon, usei por um ano o Ubuntu mas ele nunca se deu muito bem com minha placa de video. Instalei o Mint pra testar e não mudei mais, ele é muito fácil, funcionou perfeitamente bem com minha placa de video e é baseado no Ubuntu por isso não senti dificuldades.

**Comment by mahenrique94** [comment]
Recomendaria Ubuntu ou Elementary.

**Comment by samuelsilvadev** [comment]
Então, atualmente estou usando o deepin, uma distro maravilhosa, leve e fácil de manipular. Usei Elementary OS, muito boa também e muito bonita, porém com uns 6meses  de uso começou a dar muito bug no meu pc..

**Comment by allangrds** [comment]
Para mim, acho que no fim das contas o que vai contar é a afinidade. Eu vou de **Lubuntu**, mas tem alguns colegas do meu trabalho que usam **Ubuntu**, **Debian**, **Fedora** e **Arch**. Claro que cada tem seus pontos fortes e fracos, mas tente ir para alguma distro popular, pq o resto será mais experiência sua como usuário do S.O do que realmente alguma mudança no workflow de desenvolvimento.

**Comment by danilosilvadev** [comment]
I3WM = S2

**Comment by calexandrepcjr** [comment]
Gentoo, Arch... kkkk

Acho que isso é mais aberto a seu gosto pessoal e proximidade com o software livre. Muitas vezes você vai querer se aprofundar no SO por paixão pela área ou querer evoluir em low level e outras vezes você vai escolher uma distro que seja pronta o bastante para te dar produtividade. Geralmente os desenvolvedores usam Ubuntu/Fedora (e todas suas distribuições irmãs/forks) no ambiente de trabalho justamente visando um ambiente mais produtivo possível. 

Se você está fazendo esta pergunta, comece com elas. Caso cresça a curiosidade ou 'amor' pela filosofia Unix, procure distros mais cruas que irão exigir mais da sua expertise. 

A escolha não é muito complexa inicialmente, só se você quiser realmente ser um usuário avançado que entenda profundamente o SO.
