### ISSUE TITLE
Carreira em cidade do interior

### ISSUE THREAD

**Issue by leonardovilarinho** [training-center/forum#47]
Olá pessoal,

sou de cidade do interior, onde a área de tecnologia não chega nem perto de ser atrativa, apesar de ter universidades com cursos voltados amplamente à tecnologia.

A opção mais viável nesse caso seria a mudança de cidade, tive essa oportunidade, uma chance em uma grande empresa, mas não estava pronto para fazer tal mudança.

Alguma pessoa aqui vive em cidade desse tipo e se manter como desenvolvedor? Se sim, como? Poderia passar dicas?

Sei que trabalho remoto é uma alternativa, mas apesar de ter uma carreira boa (para quem não têm acesso aos grandes polos), não consigo um emprego desse tipo.

Obrigado desde já.

**Comment by thaymara** [comment]
Olá!
O "não atrativa" você quer dizer especificamente o que? Que as empresas não oferecem vagas com uma tecnologia atual?
Que se for isso mesmo o que eu entendi, eu passei (e passo) pela mesma situação. Moro em uma cidade que a área de tecnologia é muito atrasada em relação a outras empresas dos grandes polos e as que são um pouco mais avançadas não oferecem novas vagas (isso porque tem bastante faculdades de TI na cidade).
O que eu acabei fazendo foi procurar empresas nas regiões ou próximas, tanto que agora trabalho em uma empresa que fica a 1h20 da onde eu moro e vou de fretado todos os dias, é cansativa a rotina, mas foi a alternativa que eu consegui encontrar para não ter que mudar. Ou o que eu vi alguns amigos fazendo foi, "aceitar" as vagas que as empresas da cidade ofereciam, mas ainda continuaram estudando a linguagem/tecnologia que eles queriam trabalhar para estarem preparados para quando surgisse alguma vaga na área que eles queriam.

**Comment by leonardovilarinho** [comment]
Olá @thaymara, o "não atrativa" se refere mais pela qualidade da empresa e oportunidade de crescimento.

Infelizmente, essa situação é difícil. Por enquanto o plano atual que encontrei é tentar ver se consigo uma renda boa na cidade mesmo (ainda não sei como, acho que será indo para essas empresas mesmo), caso não consiga, quando tiver mais preparado, ir atrás de alguma vaga em.uma cidade próxima aqui, onde já consegui mas não pude ir.

**Comment by gss-patricia** [comment]
Olar!!!

Eu moro no interior tbm, a cidade onde moro é uma cidade satélite da região de Campinas. A cidade onde moro, tem faculdades com cursos na área de TI e também tem algumas empresas que estão contratando como a IBM, porém no meu caso, eu preferi trampar em uma empresa em Campinas (Campinas é um importante polo tecnológico), gasto cerca de 1h de transito para ir e mais de 1h para voltar, isso de carro. Contudo, eu gosto de onde trabalho e depois de um tempo, conversando, fico duas vezes na semana home office. Existem várias empresas de TI que oferecem o beneficio de trabalhar home office.

**Comment by omarkdev** [comment]
Olá!

Cara, eu vou contar como foi para mim pois eu estava na mesma situação que você, no começo.

Eu morava numa cidade com 12 mil habitantes que não tinha hospital (infelizmente é serio). Sempre visei morar em outra cidade, já que a que morava não tinha nada na área de desenvolvimento de software, porém para morar em outra cidade eu precisava ser maior de idade. Comecei a fazer freelas para poder gerar uma grana e foi ai que fiz bastante networking e cosnegui fechar bastante projetos, era basicamente um trabalho remoto mas meio que para todo mundo rs, logo após fazer 18 eu passei na FATEC em Bauru e mudei para cá e continuei fazendo freela, só depois de um ano achei uma empresa que me interessava e fui trabalhar nela.

Eu acho que a sua situação é bem parecida como que foi a minha, pois a alternativa era trabalho home office ou mudar de cidade.

> Sei que trabalho remoto é uma alternativa, mas apesar de ter uma carreira boa (para quem não têm acesso aos grandes polos), não consigo um emprego desse tipo.

Eu não sei como é a sua situação, como você vive, então não posso falar para você que essa é a receita até porque tem outros fatores pessoais que influenciam. Quando eu comecei a fazer freela, tive muitas propostas recusadas, e eu sempre perguntei qual era a razão de não ter conseguido (algumas vezes era por valor, outras por habilidade técnica e algumas vezes eles nem respondiam o motivo), como na época eu tinha MUITO tempo eu comecei a estudar as principais tecnologias que apareciam em propostas de freelas.

Basicamente o que eu quero te dizer é o seguinte (não trate como regra, pode ser que não seja assim, mas foi essa visão que eu tive): A minha cidade não vai mudar do dia para noite e se tornar um polo tecnológico, então eu precisava agir fora dali para poder realizar aquilo que queria, então enquanto eu não posso mudar de cidade eu me torno tecnicamente capacitado para trabalhar na minha cidade como home office.

Deu pra entender?

**Comment by ghost** [comment]
Olá!

Bom, eu vou contar como está acontecendo comigo. 

Eu moro em Uberaba - MG, no triângulo mineiro, uma cidade que não é tão pequena, mas deixa a desejar na área de tecnologia quando se trata de oportunidades, tecnologias utilizadas e remuneração.

No início da graduação (Engenharia de Computação) eu nunca consegui achar algo na área de desenvolvimento (nem de automação, o foco do curso) que me garantissse conseguir pagar a mensalidade e trabalhar na área, por esse motivo, eu sempre trabalhei com qualquer outra coisa, até instalando TV a cabo. Quando vi que gostava bem mais da área de desenvolvimento, fui conhecendo as vertentes da área em palestras, eventos e nas próprias aulas, eu mudei para Sistemas de Informação e consegui um desconto de 50% na mensalidade, o que pela primeira vez me possibilitou aceitar um estágio como desenvolvedor. Não era nem de longe a tecnologia mais avançada e as técnicas e práticas utilizadas não eram as melhores, não utilizavam nenhuma metodologia ágil, mas era minha porta de entrada. Isso é um padrão, infelizmente, em várias empresas aqui da cidade, algo que descobri conversando com alguns programadores que trabalham nelas.

Hoje, graças a Deus, estou estagiando em uma das poucas empresas referência da cidade, que utiliza SCRUM como metodologia ágil, utiliza Angular, NodeJS, MongoDB, entre outras tecnologias em diversos de seus produtos, e oferecem treinamentos gratuitos pra gente nestes e em outros assuntos.

Pra uma cidade de interior como Uberaba, esta foi minha salvação! Porém já conversei com alguns programadores que me dão dicas excelentes no dia-a-dia sobre oportunidades fora daqui, já que converso abertamente com eles sobre carreira, vagas, oportunidades, inclusive com os donos da empresa.

Quase sempre, acredito eu, a remuneração será menor do que em empresas instaladas em grandes cidades, porém o custo de vida é proporcionalmente maior. Ou seja, toda decisão deve ser tomada baseando-se onde você deseja chegar, no seu estilo de vida, na sua motivação dentro da empresa, etc.

**Comment by weltonsanches** [comment]
Oi @leonardovilarinho também passei por isso e vou contar o que fiz pra conseguir trampar por aqui.
 
Moro em uma cidade pequena (menos de 40 mil habitantes) e as maiores cidades aqui perto são Londrina e Maringá que ficam a +ou- 140 km.

Acho que os maiores problemas de cidades pequenas se resume a falta de vagas e falta de atualização (na minha cidade tem 3 empresas de software e todas usam Delphi). A troca de experiências não acontece como em cidades maiores onde tem eventos e comunidades e por isso a galera das cidade menores usa a regra do "Se está rodando, está bom".

**Falta de vagas**

Você pode considerar remoto ou freelas.
> Sei que trabalho remoto é uma alternativa, mas apesar de ter uma carreira boa (para quem não têm acesso aos grandes polos), não consigo um emprego desse tipo.

O primeiro é sempre dificil de conseguir, eu consegui o meu primeiro freela com um amigo da faculdade na cidade mesmo, você pode tentar por networking ou vender um site ou um sistema simples pra alguém ai na cidade. Depois que você tiver um portfólio fica mais fácil procurar algo online. Depois de alguns clientes você acaba não precisando procurar muito, se fizer um trabalho legal eles vão te procurar novamente quando precisar de algo.


**Falta de atualização**
A melhor forma de se atualizar é acompanhando comunidades online (o fato de você estar no TC e no Github já é ótimo).

> apesar de ter universidades com cursos voltados amplamente à tecnologia.

Se tem universidade e curso, então tem dev ou alguém interessado em ser dev. Se tem dev e interesse por isso, você pode tentar montar uma comunidade ai. Esses dias vi um cara aqui da cidade tirando uma dúvida em um grupo de front no Facebook, chamei ele e alguns amigos devs pra gente montar uma comunidade aqui na cidade pra trocar experiências, se ajudar e fazer uns eventos.  Acho que essa troca de experiências é muuuito importante (e ajuda a ter contato com outros humanos quando se trabalha remoto hehe).

**Comment by leonardovilarinho** [comment]
Bom dia, obrigado a todos a todos por compatilharem suas experiências...

@gss-patricia legal a oportunidade que você viu, mesmo com uma empresa grande perto. No meu caso é bem difícil acontecer algo parecido, a cidade mais ligada a tecnologia está á 180km e no início paga mal (< 2,5k) rs

@omarkdev entendi sim, sua história é bem parecida com a minha, na falta de oportunidade na cidade estou a cerca de 1,3 anos como freelancer e também sempre em busca de conhecimento nas tecnologias atuais.

Porém vi alguns problemas nisso: com o histórico maior de freelancer seu preço aumenta, mas a quantidade de clientes não, pois poucos estão dispostos a ter algo de qualidade no lugar de algo barato; e sobre ter mais conhecimento para ir para o mercado, depende bastante, recentemente tive muita ligação com o mercado, notei que muita empresa grande vive na gambiarra com tecnologias antigas, então pode ser meio desapontante por não usar o conhecimento estudado (nesse ponto até gostei, porque curto umas coisas mais antigas rs).

@GuimaraesJean entendo bem seu caso, conheço bastante Uberaba-MG, moro em Ituiutaba-MG e já fui bastante aí para apresentação em eventos da faculdade rs. Aqui tem ainda menos mercado, a maioria das empresas vendem software modularizados e prontos, sem qualquer manutenção, etc, o que acaba tirando as vagas de desenvolvedores. No meu caso, estava de mudança para Uberlândia, mas aconteceu alguns imprevistos e tive que gastar o dinheiro guardado e abordar o plano, pois só com o salário inicial não daria pra me estabelecer inicialmente.

Um ponto interessante que você tocou foi o networking entre desenvolvedores, etc. Que é um ponto que durante meu estágio vi que auxilia bastante, porém pra mim é inexistente, por conta dos poucos desenvolvedores da cidade serem fechados a dialogo e a maioria dos alunos das universidades estarem lá apenas "porque foi o que sobrou".

@weltonsanches realmente, como mencionei na resposta acima, o que mais sinto falta é essa troca de experiência que fico bem privado de participar (no geral, são essas issues aqui mesmo e vídeos dos eventos no youtube).

Sobre freelancer, no início tinha me juntado com um amigo da faculdade para atender a cidade, mas logo desanimei, pois o pessoal não via valor naquilo, então para sair algo o valor devia estar bem abaixo do preço justo e vi que aquele cenário não iria mudar (já tive alguns professores que tentaram e desistiram pelo mesmo motivo). Então tentei em plataformas online, a que mais deu certo foi o Workana onde tenho [12 projetos](https://www.workana.com/freelancer/c7879f1bad35ebdf8570b27f04fb5d41) concluídos, mas com o aumento de profissionais vi que está cada vez mais difícil porque os novatos acabam desvalorizando o trabalho com preços bem baixos, o que atrai o cliente (e sempre tem novato por lá).

Sobre a comunidade, aqui na cidade é bem como mencionei acima, os profissionais atuantes são bem conservadores e praticamente 100% dos alunos não estão dispostos, pois 95% estão lá sem interesse na área, infelizmente é a realidade, já tentei algumas coisas com um ou dois amigos e professores (palestras, cursos, etc) mas o desinterese é enorme.


------

Uma estratégia que estou adotando agora é enviar meu curriculo ou entrar em contato com empresas que tem possibilidades de contratação remota, mesmo que não haja vaga, apenas para criar uma comunicação. O que está até dando certo, ainda não consegui um emprego, mas existe alguma troca de experiência ali.

Por outro lado, também estou tentando produzir mais conteúdo aberto, tanto para ajudar a comunidade do TC e Vue.js Brasil, e tentar de destacar um pouco.

**Comment by mahenrique94** [comment]
Assim como a @gss-patricia, eu também optei por trabalhar em Campinas, gasto cerca de 40-50 minutos para ir e o mesmo para voltar. Além de fazer *home office* duas vezes na semana.

Aliás, sou de Mogi Guaçu.
