### ISSUE TITLE
Como masterizar JavaScript?

### ISSUE THREAD

**Issue by vinibrsl** [training-center/forum#54]
JavaScript não é uma linguagem difícil de aprender, mas concordo que seja difícil de masterizar. Prototype, closures, scopes, assincronismo e tudo mais...

Que conteúdos eu preciso saber e onde achá-los para masterizar o JavaScript? Que dicas vocês, jedis na arte do JS, me dão para me tornar um mestre nessa linguagem?

**Comment by samuelsilvadev** [comment]
Eae, tudo bele @vnbrs ?

Cara, para os meus estudos tenho usado livros e cursos. A ideia de ler livros sobre a linguagem, me fez entender muitos conceitos bacanas e me fez sentir mais confortável com a linguagem.

Segue uma lista pessoal de estudos

### Vídeo aulas

- [Javascript ninja](https://www.udemy.com/curso-javascript-ninja/) -  Esse curso é animal, por questão de money eu esperei baixar o preço pra comprar :D
- [Desvendando a linguagem Javascript](https://www.youtube.com/watch?v=093dIOCNeIc&list=PLQCmSnNFVYnT1-oeDOSBnt164802rkegc) - Uma das minhas playlists favoritas sobre JS
- [Javascript design patterns](https://br.udacity.com/course/javascript-design-patterns--ud989)
- [Domine this](https://www.youtube.com/watch?v=fBInMy61plk&list=PLy5T05I_eQYNQs4Pta85XRSucm3IOHx2M) - Nessa playlist é passada vários conceitos fodas da linguagem


### Livros

- [Learning JavaScript Design Patterns](https://addyosmani.com/resources/essentialjsdesignpatterns/book/)
- [eloquente javascript PT](https://github.com/braziljs/eloquente-javascript)
- [ES6-for-humans](https://github.com/metagrover/ES6-for-humans)
- [Secrets of the javascript ninja](https://www.manning.com/books/secrets-of-the-javascript-ninja-second-edition)


Esses conteúdos são apenas um direcionamento, tenho usado eles pra aprender um pouco. Sempre tem mais por ai :D

O mais importante é você traçar uma rota de estudos, e segui-la até o fim, isso fará a diferença.

Espero ter ajudado :D

**Comment by luizbills** [comment]
Eloquent Javascript que o Samuel recomendou é muito bom. Também já ouvi falar muito bem da série [You Don't Know Javascript](https://github.com/getify/You-Dont-Know-JS). E, não importa o conteúdo, recomendo você ler e praticar. Praticar muito mais do que ler. É a experiência que vai te tornar um "mestre" e não somente o conhecimento.
