### ISSUE TITLE
TC meetup online 

### ISSUE THREAD

**Issue by ruanvalente** [training-center/forum#59]
Galera, estava pensando em algo bacana para o TC que seriam *lives no YouTube com pequenas talks*.

Tipo o que rola no [Canaldotnet](https://www.youtube.com/channel/UCIahKJr2Q50Sprk5ztPGnVg).

É apenas uma idéia e seria legal. Ficaria mais ou menos assim:

 - 1x por mês acontecer esse pequeno meetup.
- Seria um meetup  online para a galera que não mora na região próxima ao presencial, ou por algum outro motivo não poder ir ao meetup.
- Duração no minimo *1 hora* para o evento.
- Seria *3 talks pequenas* uma após o término da outra.

E aí o que acham ? Comentem !!!

**Comment by gustavocardoso** [comment]
Eu acho interessante a idéia. Eu não consegui ir num meetup do TC até agora, pois devido ao meu horário de trabalho e da minha esposa, eu acabo pegando minha filha na escola e fico com ela!!!

:)

**Comment by woliveiras** [comment]
É uma ideia muito maneira, @ruanvalente!

Já tentamos fazer um movimento assim antes, mas não foi pra frente porque não conseguimos pessoas para cuidarem do canal.

Até mesmo, o canal está meio parado por isso. :cry: ([Canal](https://www.youtube.com/c/TrainingCenterChannel))

Temos algumas ideias pra tentar levar conteúdo em vídeo, pois é melhor do que texto para aprendizagem, mas está muito difícil o tempo para gravação, edição e moderação do canal.

Quem cuida do nosso canal é o irmão @lbighetti e ele está meio apertado de trampo.

Se tivessemos mais pessoas para ajudar e ficarem responsáveis pelos meetups online, daria pra fazer lindamente! \o/

Da pra criar um formato legal, onde as pessoas enviam propostas de palestras, assim como nos meetups presenciais, fazer um Q&A no final das palestras, segregar o conteúdo... Da pra fazer muita coisa legal se a gente tiver braço, viu.

Bora movimentar isso e tentar trazer gente?

**Comment by emanuelgsouza** [comment]
Super apoio essa ideia. Achei do caramba!

**Comment by ghost** [comment]
Ideia foda. Eu moro fora do Brasil e fico louco com os meetups e não posso ir.

**Comment by Jciel** [comment]
Ideia muito boa msm, pra galera que mora longe dos centros que acontecem os meetups.

**Comment by woliveiras** [comment]
Bora amadurecer essa ideia, galera!

Até agora temos o formato:

- 1x por mês
- online
- 1 hora de evento
- 3 talks curtas
- as pessoas enviam CFP
- a comunidade escolhe o assunto que deseja ouvir

A interação com palestrantes poderia ser depois da palestra, através de um canal dedicado a meetups online dentro do nosso Slack. Nesse canal seriam criadas trheads para as palestras do dia.

O que acham?

**Comment by Jciel** [comment]
Seriam mais ou menos qtos minutos cada talk? Uns 30min?

**Comment by woliveiras** [comment]
20 min, @Jciel 

Se pensarmos como um TED, da vida, que ocupa o tempo máximo de atenção de público, poderíamos até diminuir pra 18 min.

Lembrando que vídeos, online, costumam ocupar somente 7 min de atenção do expectador. :joy:

**Comment by Jciel** [comment]
Sim, tbm preferiria curto assim, tanto pra quem está fazendo a talk e pra quem tá assistindo, 20 min acho um bom tempo.

**Comment by gustavocardoso** [comment]
Seria, então, 20 minutos pra apresentar e Q&A!?!

**Comment by ruanvalente** [comment]
Isso aí @woliveiras  uns 20 minutos está bom, aí no caso ficaria um "apresentador", para companhar no chat o que está acontecendo, no caso ele irá coletar todas as duvidas e passar para o palestrante após o final da sua palestra. E assim, depois de tudo respondido vinha a proxima palestra. 

O que acha ?

**Comment by woliveiras** [comment]
Acho uma proposta muito maneira!

**Comment by ruanvalente** [comment]
@wilcorrea Vamos tentar fazer um pilote desse projeto ? E ver como ficaria ?? O que você acha ???

**Comment by wilcorrea** [comment]
@ruanvalente há uma grande possibilidade de você ter marcado o William errado, ao que tudo indica o certo era o @woliveiras :smile:

**Comment by woliveiras** [comment]
Sempre, @wilcorrea 

AHIIAHIAHIAHI

**Comment by woliveiras** [comment]
A galera começou a fazer aqui: https://github.com/training-center/remote-meetup

Podemos fechar essa issue e seguir tudo lá no repositório, o que acham?

**Comment by lbighetti** [comment]
Fechado @woliveiras !

obrigado todo mundo pelas excelentes idéias ! ❤️ 
em especial ao @ruanvalente por levantar essa bola e fazer essa idéia ganhar impulso de novo! :)

bora pra lá pro Repo novo people! 💪
