### ISSUE TITLE
Junção de repositórios

### ISSUE THREAD

**Issue by woliveiras** [training-center/forum#61]
Galera, temos os seguintes repositórios que ficam meio parados por serem mais de nicho:

- https://github.com/training-center/code-review
- https://github.com/training-center/primeiro-trampo
- https://github.com/training-center/code-house

Como o forum está começando a movimentar legal, o que acham de unirmos logo os três ao forum e as pessoas poderem pedir code review, enviar vagas e/ou deixar seus perfis disponíveis e buscarem local para passar temporadas aqui neste repo e usarmos **tags** para gerenciar tudo?

**Comment by woliveiras** [comment]
Poderíamos usar o forum para "anúncios da direção" e para dúvidas sobre a nossa comunidade também.

Assim centralizamos a informação e as pessoas podem seguir somente um projeto ao invés de procurar coisas em diversos projetos.

**Comment by luizbills** [comment]
Acho que o de jobs podia continuar separado, para ser mais focado. Os outros concordo em unir ao fórum.

**Comment by liviagabos** [comment]
Concordo com o @luizbills, talvez o de jobs poderia ficar separado.
Fica mais fácil de pesquisar unindo as informações.

**Comment by woliveiras** [comment]
Da hora!

Acabou que esqueci de retomar aqui, galera, me desculpem.

Eu conversei com mais gente também e cheguei a conclusão que poderia poluir o forum ao invés de ajudar... 

O que vou fazer será citar os outros projetos aqui no README pra galera saber que existe e colar pra lá também. \o/

**Comment by woliveiras** [comment]
Vou fechar a issue por isso.

Valeeeeu!
