### ISSUE TITLE
Tecnologias Microsoft

### ISSUE THREAD

**Issue by mikaelhadler** [training-center/forum#64]
Olá pessoal. Adoraria uma opinião de vocês sobre soluções Microsoft, se aos que puderem responder com seriedade, por favor o façam!

Sou desenvolvedor Web, particularmente nunca gostei muito de trabalhar com aplicações Microsoft, por na época depender de sua IDE que eu particularmente tinha ranço, pois bem, atualmente, tenho maior familiaridade com Javascript e seus principais frameworks.

Vejo que o posicionamento da Microsoft quanto ao uso de tecnologias abertas mudou e gostei de saber que a galera está colaborando bastante.

A minha dúvida é a seguinte.

Vocês que já trabalham com aplicações Web utilizando soluções Microsoft.

Por que utilizam Microsoft? Quais as principais tecnologias que mais lhe dão abertura ao mercado de trabalho como um programador Jr/Pleno?

Tive está dúvida devido a grande demanda de profissionais Microsoft que tem surgido, não sei se é por que a tecnologia é um saco de se trabalhar e por isso pagam bem ou se por outro motivo que desconheço.

Poderiam me ajudar nessa análise?

**Comment by lbighetti** [comment]
Sou mantenedor de um app C# usando Azure / windows server pra deploy. Já desenvolvi alguns outros apps  em C# quando eu trabalhava em banco.

Minha opinião é a seguinte: Linguagens de programação são ferramentas, e C# é uma boa ferramenta, especialmente quando utilizado com Azure.

Eu trabalhei 5 anos com Java, e C# concordo que tá no mesmo barco. Tem um ecossistema extremamente estável, tem tooling e IDEs excepcionais, e eu particularmente gosto do LinQ pro banco de dados, que inclusive serviu de inspiração pro Ecto do Elixir, minha lib preferida de banco de dado.

Eu acho que C# é uma boa linguagem pra backend ? *Com certeza!* Especialmente no paradigma OO, C# é uma aposta muito boa como linguagem pra se aprender porque, goste ou não da microsoft, ela investe um dinheiro estúpido no C# e nesse ecossistema, o que te dá uma garantia que não vai sair de linha no futuro próximo, e que vai continuar tendo inovações, atualizações e novos features bacanas, e ai entra o Azure também. O Azure é muito bom, e tudo em C# funciona super fácil e integrado lá, a experiência é muito boa!

Tem também agora o Xamarin, que dá pra fazer apps Android, IOS e Windows, tudo no mesmo codebase em C#. Eu pessoalmente acho isso extremamente poderoso.

No exterior, tem um monte de vaga de Unity que utiliza C#. Eu vejo direto aqui. Especialmente com essa onda de oculus rift/óculos virtual e essas paradas, vem aumentando bastante esse mercado e demanda por devs nesse perfil.

Enfim, não é algo que eu gosto pois acho que meus dias de OO já se foram ehhehe mas acho C# tão sólido quanto Java, apenas com o perfil diferente.

**Comment by Predoff** [comment]
Já trabalhei três anos com .NET, durante esses anos desenvolvi algumas aplicações web, desktop e mobile utilizando os frameworks ASP.NET MVC (Web), WPF (Desktop), Windows Forms (Desktop) com a linguagem C#. 

Eu acredito que o ambiente Windows facilita muito para quem está começando na área, a IDE (Visual Studio) da Microsoft é boa e como o @lbighetti falou, o C# é uma boa linguagem.

O que me incomodava bastante era a comunidade, pouca gente engajada. Outra coisa era que tinha MUITO conteúdo sobre as tecnologias (livro, blog, post, etc), porém a maioria com baixa qualidade.

O que eu gostava bastante era a facilidade de integrar o software com dispositivos externos como: kinect (lógico, é da microsoft), webcam, câmera profissional, microfone, leitor RFID, etc.

**Comment by jhonattan-santos** [comment]
Também tive está dúvida tenho percebido aumento na demanda de profissionais para plataforma .NET, em empresas que pagam o valor justo para dev. jr. e muitas vagas em empresas para soluções da Microsoft.

**Comment by mikaelhadler** [comment]
Obrigado pela opinião @lbighetti ! :+1:
