### ISSUE TITLE
Má conduta no Slack

### ISSUE THREAD

**Issue by ghost** [training-center/forum#68]
Para o pessoal que participa do Slack, talvez tenha visto a história que se desenrolou hoje no canal de #vagas e sabe do que se trata. 

Seguindo a orientação do @woliveiras, estou abrindo essa Issue pra procurar uma solução.

Uma participante ao ser solicitada que continuasse uma discussão sobre uma vaga de estágio nas threads ou em outros canais, foi ofensiva com um dos membros, e esta não foi a primeira vez que isso ocorreu, visto que já ouve comportamento parecido em uma discussão sobre vagas inclusivas no mercado de trabalho. 

O print (removido após edição) mostra a situação em que ela chama um membro de "babaca", outros de "imbecis", logo após um membro solicitar que a conversa continuasse no local adequado.

 
Na imagem acima, mostra ela chamando os membros de covardes, e nas threads utilizando-se de termos ofensivos para retrucar, em vez de argumentar, como manda o bom-senso.

Enfim, a @alinebastos, que acompanhou a história, tentou acalmar a história e fazer o assunto voltar a vaga, o que foi a coisa certa a se fazer. Porém, a minha conta e, provavelmente, a do outro rapaz que solicitou que a conversa continuasse no outro canal foram bloqueadas, e não entendo o por que, visto que não foi feita nenhuma ofensa, e pelo contrário, recebemos vários tipos de xingamentos.

Gostaria que a moderação do Slack reavaliasse a situação e lembrasse do que prega o [Código de Conduta](https://github.com/training-center/sobre/blob/master/CONDUCT.md) do Training Center.

Abaixo, seguem prints do canal enviadas por um amigo que é participante do grupo, que mostram as mensagens  deletadas: 

(prints removidos e reportados à moderação)

Ao pessoal da moderação do Slack que veja essa Issue, por favor, verifique a nossa situação, já que estamos lá para discutir ideias abertamente, e principalmente, adquirir e compartilhar conhecimento.

Muito obrigado, desde já.

**Issue editada**

**Comment by alinebastos** [comment]
E tu acha que tu ta fazendo melhor abrindo uma issue num forum público pra expor uma pessoa e os prints de um grupo fechado?

**Comment by gustavocardoso** [comment]
Cara, reporte a situação, caso tú tenha se sentido ofendido ou qualquer coisa. Mas, por favor, apague esses prints. Você está expondo uma pessoa publicamente!

**Comment by ghost** [comment]
Fui orientado a abrir essa Issue por uma pessoa responsável pelo Training Center. Além disso, não entendi o motivo da minha conta bloqueada, então estou procurando aqui ajuda da moderação, pra resolver a situação.

**Comment by ohgosch** [comment]
@GuimaraesJean com esta issue você está ferindo o código de conduta do TC.

> - Nós respeitamos limites, identidade e privacidade das pessoas;

Reporte a situação para o core e não exponha os envolvidos com print's e acusações de forma pública. Está aí um possível motivo de estar bloqueado.

**Comment by alinebastos** [comment]
Bom, eu também sou responsável pelo TC e estou te dizendo que esta não é a maneira. Tu tá expondo alguém publicamente.

**Comment by ghost** [comment]
Certo, Issue editada. 

Agora preciso saber quem pode resolver essa situação. Imagino que a referida pessoa continue no grupo após ter ofendido vários membros, enquanto minha conta continua deletada.

**Comment by woliveiras** [comment]
Galera, sobre usar o forum para expor um problema, isso é um ato democrático dentro de uma comunidade.

Qualquer pessoa deve ter o direito de fazer isso, viu.

Então é correto sim abrir uma issue para debater sobre qualquer coisa envolvendo a comunidade para que a pessoa que reportou tenha apoio da comunidade, além da moderação.

Só a questão dos prints que deveriam ser enviados via formulário de denúncia, [esse aqui](https://trainingcentr.typeform.com/to/P09LMl)

**Comment by DRS90** [comment]
1. Não vi quem mandou os 'kkkk' (antes dos prints serem deletados), mas não parece muito respeitoso rir na cara de uma pessoa, muito menos argumentativo;
2. No canal de vagas parecia o lugar adequado, já que estava em uma thread (para não ter poluição) e por se tratar de uma vaga;
3. Não acompanhei a discussão, só vi os prints rapidamente, mas já aconteceu de pessoas terem sido banidas antes e mereciam com todas as forças

**Comment by woliveiras** [comment]
Não tem outros modos de levantar seus pontos sem ser com os prints, @GuimaraesJean?

**Comment by ghost** [comment]
@woliveiras, não porque as mensagens ofensivas foram deletadas e minha conta está bloqueada. Os prints são as únicas provas que consigo agora. E se for o caso, reedito e coloco as prints novamente.


@DRS90, muito mais desrespeitoso é chamar de "imbecil, covarde, escroto, babaca e mandar tomar no **". 
Além disso as mensagens entraram na thread muito tempo depois que a Aline solicitou, porque no começo foram só mensagens de discussão e ofensa sem sentido.

**Comment by alinebastos** [comment]
@GuimaraesJean tu me mencionou o teu post como sendo quem chegou e orgaizou tudo, mas no momento de reportar tu foi procurar o Will, que nem estava na hora, e não a mim. Pq?

**Comment by ghost** [comment]
Pelo fato de ele ser o moderador com quem tive mais contato. Já precisei de orientações a respeito de outros assuntos, outros canais e outras iniciativas do Training Center, e todas as vezes me dirigi a ele.

**Comment by mikaelhadler** [comment]
Quanto a postar prints em público e não reportar direto a uma dos moderadores isso foi completamente anti senso :S. Queria ressaltar que como integrante de TC, sei que inúmeras vezes as meninas recebem uma porrada de comentário imbecil e desrespeitoso que muita das vezes são feitas por pessoas babacas, @GuimaraesJean , há de se ter bom senso e cautela quando pode se ferir uma pessoa.

Acredito que foi uma atitude prudente de banimento e o que for necessário, visto que já vemos inúmeros casos de insultos as minorias quando somente estão expondo algo.

**Comment by woliveiras** [comment]
> não porque as mensagens ofensivas foram deletadas e minha conta está bloqueada. Os prints são as únicas provas que consigo agora. E se for o caso, reedito e coloco as prints novamente.

Não, mano... Os prints devem ser enviados, se você for fazer, via formulário de denúncia, não aqui, viu.

No caso, a comunidade tem um grupo de moderadores e eles discutiram antes de te bloquear.

A @alinebastos é moderadora, temos o @lbighetti, @gustavocardoso e mais uma galera que não me recordo.

Se eles concordaram em expulsar, deve ter tido algum motivo, como o @DRS90 comentou.

O ideal agora seria questionar para entender o que fez de errado para aprender como corrigir/mudar/melhorar.

Eu mesmo não tenho poder algum, afinal a comunidade é um grupo, não sou eu. Eu só posso ajudar a argumentar, mas nesse caso eu não consigo apoiar, porque não vi a discussão e não sei do contexto, mas, como falei, se o pessoal votou por block, é aceitar a decisão, assim como eu aceitaria se eu fosse expulso por decisão do grupo.

**Comment by ghost** [comment]
@mikaelhadler, a questão é que não houve comentário ofensivo. O outro rapaz sugeriu que a conversa continuasse num canal mais adequado, ou em threads, como a Aline sugeriu (estava no print que removi).

A resposta logo abaixo foi "**não se meta, não venha me dizer o que fazer**". Um pouco mais abaixo "**estão rindo de que, seus imbecis**?". E um pouco mais abaixo "**É por isso que nunca serão homens de verdade, apenas crianças que nem sabem limpar a própria bunda ainda. Além de rirem como se tivessem tendo um ataque de pelanca. São covardes, sempre o serão**". 

Na thread, que se iniciou depois, a pessoa a quem me refiro me mandou tomar no **, então acho que se alguém foi ofensivo aqui e deveria ser banido, deveria ser ela. Ou pelo menos que seja justo, retire o banimento meu e de quem quer que tenha sido junto.

Não houve ataque, foi só agressão gratuita com alguém que discordou do que ela disse, algo que já aconteceu numa divulgação de uma vaga e iniciou-se uma discussão sobre a vaga ser ou não inclusiva.

**Comment by ghost** [comment]
@alinebastos , você, que acompanhou em tempo real e sabe do que se trata a situação, viu em algum momento qualquer um de nós a ofender?

E se esse tipo de conduta é intolerável, fui banido por ter sido ofendido, o que não faz o menor sentido. O que o @mikaelhadler disse faz todo sentido, existem muito comentários agressivos às minorias, mas este não foi o caso, e você pode ver nos prints, assim como viu no momento em que aconteceu.

**Comment by mikaelhadler** [comment]
Cara, não existe agressão gratuita no TC, a moderação é mais que competente para saber o que é correto, justo, pois como o @woliveiras  falou, somos uma comunidade! Se a pessoa se sentiu ofendida por atos que você mesmo citou, "estão rindo de que, seus imbecis?", como não interpretar como uma ofensa ? Eu não acho graça quando alguém ta expondo uma thread séria quanto as características de uma vaga, caberia a ela interagir com o recrutador ou a pessoa que passou a vaga e não alheios.

 "E se esse tipo de conduta é intolerável, fui banido por ter sido ofendido", cara você ta entendendo a gravidade do que você ta falando ? Você está subjugando a decisão de um núcleo de uma comunidade que é inclusiva. CONFIO PLENAMENTE nas decisões do core do TC.

@GuimaraesJean Quanto a você não ter feito nada, eu não acredito mano, você não seria banido por nada, to total ciente disso.

**Comment by ohgosch** [comment]
Se você foi banido, é porque alguém não gostou da(s) sua(s) atitude(s). A moderação analisou os fatos e foi visível que a integrante não gostou da atitude de um dos integrantes mandar que a conversa fosse mudada de local (mutando quem estava debatendo sobre a vaga). Ela teve uma reação às "ordens" dele. Após vimos um deboche partindo de você, como se o COC não valesse para todos os membros. O que é uma ofensa pra nós que trabalhamos arduamente (principalmente a @alinebastos) para que tenhamos uma comunidade segura.

Repense suas atitudes ao duvidar do nosso trabalho.

**Comment by ohgosch** [comment]
Comece a se questionar o porque foi banido, e não a nos questionar o porque te banimos. Não temos motivo algum para banir um membro gratuitamente!

**Comment by DRS90** [comment]
Te convido a ir para o twitter dessa pessoa. Cara é tanta agressão e perigos que acontecem/podem acontecer diariamente com essa pessoa(só por ser quem é), que qualquer demonstração de intolerância e desrespeito é uma batalha. Xingar não é uma atitude correta, mas não foi ela que começou com o desrespeito e se eu tivesse a vivencia de luta diária eu também não teria mais paciência.
Como o @woliveiras falou, aprenda com os erros, se você foi banido existe um motivo e em vez de colocar sua opinião e ponto de vista como suprema, pense melhor.

**Comment by ghost** [comment]
Então o que vocês estão dizendo é que é normal xingar de "babaca, imbecil, covarde, mandar tomar no **, se for alguém que se sente ofendido(a) e se encaixe em alguma minoria, mas se eu sou xingado sem ter ofendido ninguém eu estou errado? 

Eu estou questionando a aplicação do Código de Conduta sim, pois foi a segunda vez que a atitude dela passou impune, e a forma de justificar é sempre ignorar a ofensa e acusar quem foi ofendido.

Infelizmente os prints não podem ser mostrados aqui, mas quem acompanhou sabe bem o que aconteceu hoje.

**Comment by alinebastos** [comment]
As pessoas que decidiram por te banir acompanharam cada palavra, tu pode ter certeza disso.

**Comment by luizbills** [comment]
@GuimaraesJean Se ponha no lugar dela e imagine pessoas rachando de rir da sua cara após alguém ter tentando te silenciar/calar. Para começo de conversa você nem devia ter se intrometido, o questionamento dela foi totalmente direcionado à pessoa que postou sobre a vaga.

Agora, se ela foi ofensiva com você? Sim, ela foi e muito. Mas quando foi que você não foi ofensivo quando alguém te atacou?

Em nenhum momento ela foi até você e te atacou sem motivo. Porém você e outros foram até ela e atacaram ela sem motivo.

**Comment by alinebastos** [comment]
"Não confunda a reação do oprimido com a violência do opressor"

**Comment by ohgosch** [comment]
@GuimaraesJean você está lendo o posicionamento do core sob sua reclamação ou estamos aqui só para enfeite?

Parece um bot, repetindo a mesma coisa tantas vezes. Para, lê e reflete.

**Comment by woliveiras** [comment]
@GuimaraesJean, mano, a galera já se decidiu... Não foi uma pessoa ou duas, mas várias. Inclusive o pessoal está comentando aqui. 

Recomendo fechar essa issue e aceitar o block do Slack.

Se alguma hora quiser conversar mais sobre isso, mas não do modo como está acontecendo aqui, pode chamar esse pessoal num Telegram da vida e buscar compreender melhor.

**Comment by ghost** [comment]
Pra que vocês tirem suas próprias conclusões, segue abaixo: 

Ao @woliveiras, obrigado pela prontidão em responder no email e aqui.

Ao @rgosch, que disse que eu ignoro o julgamento do core, eu estou expondo aqui o que houve, e que foi um julgamento errado, visto que não houve ataque gratuito, muito menos ofensa da minha parte.

Aos demais que me acusaram de ofender gratuitamente ou rir da cara da pessoa a quem me refiro, vejam os prints e tirem suas conclusões.

![whatsapp image 2018-03-26 at 17 22 33](https://user-images.githubusercontent.com/9667175/37939858-a9ea09d4-313b-11e8-86a8-aace92191032.jpeg)
![whatsapp image 2018-03-26 at 17 22 33 1](https://user-images.githubusercontent.com/9667175/37939859-aa1aec02-313b-11e8-876f-9b94af47881f.jpeg)

**Comment by evlymn** [comment]
@GuimaraesJean  Pode deixar os prints, pois só um babaca mesmo para fazer uma coisa dessa.
E outra, vá chorar a puta que te pariu seu idiota!!!!
Comigo, omi escroto não tem vez, e essas regras, é pra gente igual a ti, uma criança de merda que mal sabe limpar a bunda.
Sim, tem dois pesos e duas medidas, o peso e medida que eu dou a quem se mete comigo.

**Comment by evlymn** [comment]
kkkkkkkkkkk
@GuimaraesJean  to rindo muito da tua imbecilidade nos comentários.
Chora mais que tá lindo ver esse projeto de homem se rebaixando tanto kkkkkkkk

**Comment by evlymn** [comment]
Ps: tu já me expos, minha advogada já está sabendo.
Portanto, quero ver tu ser homem a partir de agora

**Comment by evlymn** [comment]
E outra menino mimimi, eu não tenho medo de guri cagão...
Aviso a todos aqui, vcs não sabem com quem se meteram
Lembrem-se, quando eu falo, homem cala a boca. 
Tendido?

**Comment by Vitor-Felipe** [comment]
Eu estava acompanhando a situação em tempo real @luizbills e não foi o @GuimaraesJean que riu dela e sim outros 2 membros, que aliás, estavam rindo de um insulto que a @jelielmendes fez a eles (melhor resposta possível para aquela situação). Agora, várias outros insultos dela, foram apagados da conversar e apenas os rapazes foram banidos (sem motivo). Vale lembrar que a @jelielmendes disse que as regras de conduta não se aplicavam a ela, isso logo após o @GuimaraesJean disser sobre o mesmo.

E sinceramente, olha os comentários dela (@jelielmendes)  aqui na própria issue:

> "Lembrem-se, quando eu falo, homem cala a boca."

>"Chora mais que tá lindo ver esse projeto de homem se rebaixando tanto kkkkkkkk"

É revoltante ver uma situação dessa... Esperava que os moderadores analisassem o fato ocorrido, sem se importar com a pessoa ou o sexo dela.

**Comment by evlymn** [comment]
kkkkk
@Vitor-Felipe vai chorar com o amiguinho é?
As regras valem para imbecis como vcs, é para entenderem que idiotas não tem mais vez.
Achei que tinha ficado claro

**Comment by Vitor-Felipe** [comment]
Estou só relatando o que aconteceu @jelielmendes .

**Comment by evlymn** [comment]
@Vitor-Felipe qual a parte do Quando eu falo homem cala a boca vc não entendeu?

**Comment by evlymn** [comment]
Acho que vcs não entenderam, ou soma, ou some.
Não existe mais espaço para caras com pensamentos iguais aos de vcs.
Daqui pra frente serão coadjuvantes, como sempre foram, apenas gritavam mais e davam piti demais
Isso acabou

**Comment by Vitor-Felipe** [comment]
É muito ridículo esse tipo de comportamento numa comunidade de compartilhamento de informação.
Lamentável.

**Comment by evlymn** [comment]
Tadinho.... o gurizinho cagão está se sentindo oprimido... 
Não dá uma vontade de abraçar e abraçar, abraçar bem forte, mas beeeem forte, até parar de respirar? 
É só o que penso quando vejo um menino desses desamparado kkkkkk

**Comment by luizbills** [comment]
@Vitor-Felipe já deu, cara. Até o agressor já entendeu o lugar dele.

**Comment by alinebastos** [comment]
> É revoltante ver uma situação dessa... Esperava que os moderadores analisassem o fato ocorrido, sem se importar com a pessoa ou o sexo dela.

Primeiro que não é sexo, é gênero.
E se tu tá dizendo isso então tu não entendeu NADA do código de conduta e não entende NADA de inclusão.

**Comment by azromero** [comment]
Relaxa cara, TPM... daqui uma semana passa..

Em 26 de março de 2018 20:57, Jean Carlos <notifications@github.com>
escreveu:

**Comment by evlymn** [comment]
É, é o que eu digo, comunidades são um antro de omi babaca, igual ao @azromero 
E esse é dos babacas profissionais

**Comment by mikaelhadler** [comment]
Vai com teu machismo e cinismo pra puta que pariu @azromero , como @jelielmendes disse acima, ou soma ou some.

**Comment by azromero** [comment]
Thug Life

2018-03-27 11:49 GMT-03:00 Mikael Hadler <notifications@github.com>:

**Comment by evlymn** [comment]
kkkk deve ser difícil ser um imbecil como vc mesmo kkkk
Gente, as comunidades de TI devem acabar

**Comment by lbighetti** [comment]
@azromero já está banido do TC tb.
👍
