### ISSUE TITLE
[Dúvida] O mentoria ainda está aberto?

### ISSUE THREAD

**Issue by ghost** [training-center/forum#77]
Estou querendo arrumar um mentor. Queria umas dicas pra arrumar um trabalho remoto (:

**Comment by luizbills** [comment]
Só seguir esses passos: https://github.com/training-center/mentoria#preciso-de-mentoria

**Comment by woliveiras** [comment]
Podemos fechar essa issue?

**Comment by ghost** [comment]
Pode sim (: @woliveiras
